/obj/machinery/r_n_d/protolathe
	name = "Master Control Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe

/obj/machinery/r_n_d/protolathe/security
	name = "Security Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe/security
	LockedDesigns = list(/datum/design/item/weapon/energy/protector,
/datum/design/item/weapon/energy/sickshot,
/datum/design/item/weapon/energy/netgun,
/datum/design/item/weapon/pummeler,
/datum/design/item/weapon/ballistic/ammo/ammo_9mmAdvanced,
/datum/design/item/weapon/ballistic/ammo/stunshell,
/datum/design/item/weapon/ballistic/ammo/empshell,
/datum/design/item/weapon/ammo/flechette,
/datum/design/item/weapon/ammo/dartgunmag_small,
/datum/design/item/weapon/ammo/dartgun_ammo_small,
/datum/design/item/weapon/ammo/dartgunmag_med,
/datum/design/item/weapon/ammo/dartgun_ammo_med,
/datum/design/item/weapon/grenade/large_grenade,
/datum/design/item/pda_cartridge/security,
/datum/design/item/hud/security,
/datum/design/item/gps/security)

/obj/machinery/r_n_d/protolathe/cargo
	name = "Cargo Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe/cargo
	LockedDesigns = list(/datum/design/item/hud/material,
/datum/design/item/hud/graviton_visor,
/datum/design/item/weapon/mining/drill,
/datum/design/item/weapon/mining/advdrill,
/datum/design/item/weapon/mining/jackhammer,
/datum/design/item/weapon/mining/plasmacutter,
/datum/design/item/weapon/mining/pick_diamond,
/datum/design/item/weapon/mining/drill_diamond,
/datum/design/item/weapon/mining/depth_scanner,
/datum/design/item/weapon/mining/upgradeAOE,
/datum/design/item/weapon/mining/mining_scanner,
/datum/design/item/tool/experimental_welder,
/datum/design/item/tool/hand_drill,
/datum/design/item/tool/jaws_life,
/datum/design/item/hud/mesons,
/datum/design/item/precursor/crowbar,
/datum/design/item/precursor/wrench,
/datum/design/item/precursor/screwdriver,
/datum/design/item/precursor/wirecutters,
/datum/design/item/precursor/welder,
/datum/design/item/powercell/basic,
/datum/design/item/powercell/high,
/datum/design/item/powercell/super,
/datum/design/item/powercell/hyper,
/datum/design/item/powercell/device,
/datum/design/item/powercell/advance_device,
/datum/design/item/powercell/super_device,
/datum/design/item/powercell/hype_device,
/datum/design/item/powercell/omni_device,
/datum/design/item/stock_part/basic_matter_bin,
/datum/design/item/stock_part/adv_matter_bin,
/datum/design/item/stock_part/super_matter_bin,
/datum/design/item/stock_part/hyper_matter_bin,
/datum/design/item/stock_part/omni_matter_bin,
/datum/design/item/stock_part/micro_mani,
/datum/design/item/stock_part/nano_mani,
/datum/design/item/stock_part/pico_mani,
/datum/design/item/stock_part/hyper_mani,
/datum/design/item/stock_part/omni_mani,
/datum/design/item/stock_part/basic_capacitor,
/datum/design/item/stock_part/adv_capacitor,
/datum/design/item/stock_part/super_capacitor,
/datum/design/item/stock_part/hyper_capacitor,
/datum/design/item/stock_part/omni_capacitor,
/datum/design/item/stock_part/basic_sensor,
/datum/design/item/stock_part/adv_sensor,
/datum/design/item/stock_part/phasic_sensor,
/datum/design/item/stock_part/hyper_sensor,
/datum/design/item/stock_part/omni_sensor,
/datum/design/item/stock_part/basic_micro_laser,
/datum/design/item/stock_part/high_micro_laser,
/datum/design/item/stock_part/ultra_micro_laser,
/datum/design/item/stock_part/hyper_micro_laser,
/datum/design/item/stock_part/omni_micro_laser,
/datum/design/item/stock_part/bundle/t1,
/datum/design/item/stock_part/bundle/t2,
/datum/design/item/stock_part/bundle/t3,
/datum/design/item/stock_part/bundle/t4,
/datum/design/item/stock_part/bundle/t5,
/datum/design/item/stock_part/RPED,
/datum/design/item/stock_part/ARPED,
/datum/design/item/gps/mining,
/datum/design/item/boh/ore_holding)

/obj/machinery/r_n_d/protolathe/service
	name = "Service Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe/service
	LockedDesigns = list(/datum/design/item/general/translator,
	/datum/design/item/general/ear_translator,
	/datum/design/item/general/light_replacer,
	/datum/design/item/general/advmop,
	/datum/design/item/general/walkpod,
	/datum/design/item/general/juke_remote,
	/datum/design/item/pda_cartridge/janitor,
	/datum/design/item/boh/trashbag_holding,)

/obj/machinery/r_n_d/protolathe/engineering
	name = "Engineering Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe/engineering
	LockedDesigns = list(/datum/design/item/engineering/t_scanner,
/datum/design/item/engineering/t_scanner_upg,
/datum/design/item/engineering/t_scanner_adv,
/datum/design/item/engineering/atmosanalyzer,
/datum/design/item/hud/mesons,
/datum/design/item/general/inducer_eng,
/datum/design/item/tool/experimental_welder,
/datum/design/item/tool/hand_drill,
/datum/design/item/tool/jaws_life,
/datum/design/item/precursor/crowbar,
/datum/design/item/precursor/wrench,
/datum/design/item/precursor/screwdriver,
/datum/design/item/precursor/wirecutters,
/datum/design/item/precursor/welder,
/datum/design/item/pda_cartridge/engineering,
/datum/design/item/powercell/basic,
/datum/design/item/powercell/high,
/datum/design/item/powercell/super,
/datum/design/item/powercell/hyper,
/datum/design/item/powercell/device,
/datum/design/item/powercell/advance_device,
/datum/design/item/powercell/super_device,
/datum/design/item/powercell/hype_device,
/datum/design/item/powercell/omni_device,
/datum/design/item/stock_part/basic_matter_bin,
/datum/design/item/stock_part/adv_matter_bin,
/datum/design/item/stock_part/super_matter_bin,
/datum/design/item/stock_part/hyper_matter_bin,
/datum/design/item/stock_part/omni_matter_bin,
/datum/design/item/stock_part/micro_mani,
/datum/design/item/stock_part/nano_mani,
/datum/design/item/stock_part/pico_mani,
/datum/design/item/stock_part/hyper_mani,
/datum/design/item/stock_part/omni_mani,
/datum/design/item/stock_part/basic_capacitor,
/datum/design/item/stock_part/adv_capacitor,
/datum/design/item/stock_part/super_capacitor,
/datum/design/item/stock_part/hyper_capacitor,
/datum/design/item/stock_part/omni_capacitor,
/datum/design/item/stock_part/basic_sensor,
/datum/design/item/stock_part/adv_sensor,
/datum/design/item/stock_part/phasic_sensor,
/datum/design/item/stock_part/hyper_sensor,
/datum/design/item/stock_part/omni_sensor,
/datum/design/item/stock_part/basic_micro_laser,
/datum/design/item/stock_part/high_micro_laser,
/datum/design/item/stock_part/ultra_micro_laser,
/datum/design/item/stock_part/hyper_micro_laser,
/datum/design/item/stock_part/omni_micro_laser,
/datum/design/item/stock_part/bundle/t1,
/datum/design/item/stock_part/bundle/t2,
/datum/design/item/stock_part/bundle/t3,
/datum/design/item/stock_part/bundle/t4,
/datum/design/item/stock_part/bundle/t5,
/datum/design/item/stock_part/RPED,
/datum/design/item/stock_part/ARPED,
/datum/design/item/gps/engineering)

/obj/machinery/r_n_d/protolathe/medical
	name = "Medical Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe/medical
	LockedDesigns = list(/datum/design/item/biotech/nif,
/datum/design/item/biotech/nifbio,
/datum/design/item/implant/sizecontrol,
/datum/design/item/general/bodysnatcher,
/datum/design/item/implant/chemical,
/datum/design/item/implant/backup,
/datum/design/item/medical/scalpel_laser1,
/datum/design/item/medical/scalpel_laser2,
/datum/design/item/medical/scalpel_laser3,
/datum/design/item/medical/scalpel_manager,
/datum/design/item/medical/saw_manager,
/datum/design/item/medical/organ_ripper,
/datum/design/item/medical/bone_clamp,
/datum/design/item/medical/medical_analyzer,
/datum/design/item/medical/improved_analyzer,
/datum/design/item/medical/advanced_analyzer,
/datum/design/item/medical/advanced_roller,
/datum/design/item/medical/phasic_analyzer,
/datum/design/item/medical/large_bodybag,
/datum/design/item/medical/sleevemate,
/datum/design/item/medical/protohypospray,
/datum/design/item/medical/recombobray,
/datum/design/item/medical/cell_based/cell_medigun,
/datum/design/item/medical/cell_based/cell_medigun_mag,
/datum/design/item/medical/cell_based/cell_medigun_mag_advanced,
/datum/design/item/ml3m_cell/brute,
/datum/design/item/ml3m_cell/burn,
/datum/design/item/ml3m_cell/stabilize,
/datum/design/item/ml3m_cell/toxin,
/datum/design/item/ml3m_cell/omni,
/datum/design/item/ml3m_cell/antirad,
/datum/design/item/ml3m_cell/brute2,
/datum/design/item/ml3m_cell/burn2,
/datum/design/item/ml3m_cell/stabilize2,
/datum/design/item/ml3m_cell/omni2,
/datum/design/item/ml3m_cell/toxin2,
/datum/design/item/ml3m_cell/corpse_mend,
/datum/design/item/weapon/rapidsyringe,
/datum/design/item/weapon/dartgun,
/datum/design/item/weapon/chemsprayer,
/datum/design/item/organ/internal/augment/armmounted/hand,
/datum/design/item/organ/internal/augment/armmounted/shoulder/multiple,
/datum/design/item/organ/internal/augment/armmounted/shoulder/multiple/medical,
/datum/design/item/pda_cartridge/medical,
/datum/design/item/pda_cartridge/chemistry,
/datum/design/item/hud/health,
/datum/design/item/gps/medical,
/datum/design/item/beaker/bluespace,
/datum/design/item/boh/belt_holding_med,
/datum/design/item/biotech/mass_spectrometer,
/datum/design/item/biotech/adv_mass_spectrometer,
/datum/design/item/biotech/reagent_scanner,
/datum/design/item/biotech/adv_reagent_scanner)

/obj/machinery/r_n_d/protolathe/exploration
	name = "Exploration Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe/exploration
	LockedDesigns = list(
/datum/design/item/precursor/crowbar,
/datum/design/item/precursor/wrench,
/datum/design/item/precursor/screwdriver,
/datum/design/item/precursor/wirecutters,
/datum/design/item/precursor/welder,
/datum/design/item/weapon/ballistic/ammo/ammo_9mmAdvanced,
/datum/design/item/weapon/ballistic/ammo/stunshell,
/datum/design/item/weapon/ballistic/ammo/empshell,
/datum/design/item/weapon/ammo/flechette,
/datum/design/item/weapon/melee/esword,
/datum/design/item/weapon/melee/eaxe,
/datum/design/item/weapon/energy/protector,
/datum/design/item/weapon/pummeler,
/datum/design/item/weapon/particle/advparticle,
/datum/design/item/weapon/particle/particlecannon,
/datum/design/item/weapon/particle/pressureinterlock,
/datum/design/item/weapon/ballistic/ammo/ptrshell,
/datum/design/item/weapon/energy/hunter,
/datum/design/item/weapon/phase/phase_pistol,
/datum/design/item/weapon/phase/phase_carbine,
/datum/design/item/weapon/phase/phase_rifle,
/datum/design/item/weapon/phase/phase_cannon,
/datum/design/item/weapon/phase/frontier_holdout,
/datum/design/item/weapon/phase/frontier_phaser,
/datum/design/item/weapon/phase/frontier_carbine,
/datum/design/item/weapon/phase/frontier_rifle,
/datum/design/item/weapon/phase/frontier_handbow,
/datum/design/item/weapon/gun/projectile/caseless/prototype,
/datum/design/item/weapon/energy/lasercannon,
/datum/design/item/gps/explorer)

/obj/machinery/r_n_d/protolathe/science
	name = "Science Protolathe"
	icon_state = "protolathe"
	circuit = /obj/item/weapon/circuitboard/protolathe/science
	LockedDesigns = list(/datum/design/item/boh/ore_holding,
							/datum/design/item/hud/material,
							/datum/design/item/hud/graviton_visor,
							/datum/design/item/weapon/mining/drill,
							/datum/design/item/weapon/mining/advdrill,
							/datum/design/item/weapon/mining/jackhammer,
							/datum/design/item/weapon/mining/plasmacutter,
							/datum/design/item/weapon/mining/pick_diamond,
							/datum/design/item/weapon/mining/drill_diamond,
							/datum/design/item/weapon/mining/depth_scanner,
							/datum/design/item/weapon/mining/upgradeAOE,
							/datum/design/item/weapon/mining/mining_scanner,
							/datum/design/item/tool/experimental_welder,
							/datum/design/item/tool/hand_drill,
							/datum/design/item/tool/jaws_life,
							/datum/design/item/tool/rpd,
							/datum/design/item/tool/rms,
							/datum/design/item/tool/rpd,
							/datum/design/item/tool/qpad_booster,
							/datum/design/item/engineering/t_scanner,
							/datum/design/item/engineering/t_scanner_upg,
							/datum/design/item/engineering/t_scanner_adv,
							/datum/design/item/engineering/atmosanalyzer,
							/datum/design/item/hud/mesons,
							/datum/design/item/general/inducer_eng,
							/datum/design/item/modularcomponent/disk/normal,
							/datum/design/item/modularcomponent/disk/advanced,
							/datum/design/item/modularcomponent/disk/super,
							/datum/design/item/modularcomponent/disk/cluster,
							/datum/design/item/modularcomponent/disk/small,
							/datum/design/item/modularcomponent/disk/micro,
							/datum/design/item/modularcomponent/netcard/basic,
							/datum/design/item/modularcomponent/netcard/advanced,
							/datum/design/item/modularcomponent/netcard/wired,
							/datum/design/item/modularcomponent/battery/normal,
							/datum/design/item/modularcomponent/battery/advanced,
							/datum/design/item/modularcomponent/battery/super,
							/datum/design/item/modularcomponent/battery/ultra,
							/datum/design/item/modularcomponent/battery/nano,
							/datum/design/item/modularcomponent/battery/micro,
							/datum/design/item/modularcomponent/cpu,
							/datum/design/item/modularcomponent/cpu/small,
							/datum/design/item/modularcomponent/cpu/photonic,
							/datum/design/item/modularcomponent/cpu/photonic/small,
							/datum/design/item/modularcomponent/cardslot,
							/datum/design/item/modularcomponent/nanoprinter,
							/datum/design/item/modularcomponent/teslalink,
							/datum/design/item/modularcomponent/portabledrive/basic,
							/datum/design/item/modularcomponent/portabledrive/advanced,
							/datum/design/item/modularcomponent/portabledrive/super,
							/datum/design/item/precursor/crowbar,
							/datum/design/item/precursor/wrench,
							/datum/design/item/precursor/screwdriver,
							/datum/design/item/precursor/wirecutters,
							/datum/design/item/precursor/welder,
							/datum/design/item/stock_part/subspace/subspace_ansible,
							/datum/design/item/stock_part/subspace/hyperwave_filter,
							/datum/design/item/stock_part/subspace/subspace_amplifier,
							/datum/design/item/stock_part/subspace/subspace_treatment,
							/datum/design/item/stock_part/subspace/subspace_analyzer,
							/datum/design/item/stock_part/subspace/subspace_crystal,
							/datum/design/item/stock_part/subspace/subspace_transmitter,
							/datum/design/item/boh/belt_holding_med,
							/datum/design/item/beaker/noreact,
							/datum/design/item/beaker/bluespace,
							/datum/design/item/biotech/mass_spectrometer,
							/datum/design/item/biotech/adv_mass_spectrometer,
							/datum/design/item/biotech/reagent_scanner,
							/datum/design/item/biotech/adv_reagent_scanner,
							/datum/design/item/hud/health,
							/datum/design/item/hud/omni,
							/datum/design/item/implant/chemical,
							/datum/design/item/implant/backup,
							/datum/design/item/medical/scalpel_laser1,
							/datum/design/item/medical/scalpel_laser2,
							/datum/design/item/medical/scalpel_laser3,
							/datum/design/item/medical/scalpel_manager,
							/datum/design/item/medical/saw_manager,
							/datum/design/item/medical/organ_ripper,
							/datum/design/item/medical/bone_clamp,
							/datum/design/item/medical/medical_analyzer,
							/datum/design/item/medical/improved_analyzer,
							/datum/design/item/medical/advanced_analyzer,
							/datum/design/item/medical/advanced_roller,
							/datum/design/item/medical/phasic_analyzer,
							/datum/design/item/medical/large_bodybag,
							/datum/design/item/medical/sleevemate,
							/datum/design/item/medical/protohypospray,
							/datum/design/item/medical/recombobray,
							/datum/design/item/medical/cell_based/cell_medigun,
							/datum/design/item/medical/cell_based/cell_medigun_mag,
							/datum/design/item/medical/cell_based/cell_medigun_mag_advanced,
							/datum/design/item/ml3m_cell/brute,
							/datum/design/item/ml3m_cell/burn,
							/datum/design/item/ml3m_cell/stabilize,
							/datum/design/item/ml3m_cell/toxin,
							/datum/design/item/ml3m_cell/omni,
							/datum/design/item/ml3m_cell/antirad,
							/datum/design/item/ml3m_cell/brute2,
							/datum/design/item/ml3m_cell/burn2,
							/datum/design/item/ml3m_cell/stabilize2,
							/datum/design/item/ml3m_cell/omni2,
							/datum/design/item/ml3m_cell/toxin2,
							/datum/design/item/ml3m_cell/corpse_mend,
							/datum/design/item/weapon/rapidsyringe,
							/datum/design/item/weapon/dartgun,
							/datum/design/item/weapon/chemsprayer,
							/datum/design/item/weapon/ammo/dartgunmag_small,
							/datum/design/item/weapon/ammo/dartgun_ammo_small,
							/datum/design/item/weapon/ammo/dartgunmag_med,
							/datum/design/item/weapon/ammo/dartgun_ammo_med,
							/datum/design/item/weapon/grenade/large_grenade,
							/datum/design/item/organ/internal/augment/armmounted/hand,
							/datum/design/item/organ/internal/augment/armmounted/shoulder/multiple,
							/datum/design/item/organ/internal/augment/armmounted/shoulder/multiple/medical,
							/datum/design/item/hud/security,
							/datum/design/item/implant/freedom,
							/datum/design/item/general/binaryencrypt,
							/datum/design/item/general/chameleon,
							/datum/design/item/general/riflescope,
							/datum/design/item/weapon/energy/stunrevolver,
							/datum/design/item/weapon/energy/nuclear_gun,
							/datum/design/item/weapon/energy/phoronpistol,
							/datum/design/item/weapon/energy/decloner,
							/datum/design/item/weapon/energy/vinstunrevolver,
							/datum/design/item/weapon/ballistic/advanced_smg,
							/datum/design/item/weapon/ballistic/ammo/ammo_9mmAdvanced,
							/datum/design/item/weapon/ballistic/ammo/stunshell,
							/datum/design/item/weapon/ballistic/ammo/empshell,
							/datum/design/item/weapon/fuelrod,
							/datum/design/item/weapon/ammo/flechette,
							/datum/design/item/weapon/melee/esword,
							/datum/design/item/weapon/melee/eaxe,
							/datum/design/item/weapon/energy/protector,
							/datum/design/item/weapon/energy/netgun,
							/datum/design/item/weapon/pummeler,
							/datum/design/item/weapon/particle/advparticle,
							/datum/design/item/weapon/particle/particlecannon,
							/datum/design/item/weapon/particle/pressureinterlock,
							/datum/design/item/weapon/ballistic/ammo/ptrshell,
							/datum/design/item/weapon/energy/hunter,
							/datum/design/item/weapon/phase/phase_pistol,
							/datum/design/item/weapon/phase/phase_carbine,
							/datum/design/item/weapon/phase/phase_rifle,
							/datum/design/item/weapon/phase/phase_cannon,
							/datum/design/item/weapon/phase/frontier_holdout,
							/datum/design/item/weapon/phase/frontier_phaser,
							/datum/design/item/weapon/phase/frontier_carbine,
							/datum/design/item/weapon/phase/frontier_rifle,
							/datum/design/item/weapon/phase/frontier_handbow,
							/datum/design/item/weapon/gun/projectile/caseless/prototype,
							/datum/design/item/boh/trashbag_holding,
							/datum/design/item/biotech/plant_analyzer,
							/datum/design/item/general/light_replacer,
							/datum/design/item/general/advmop,
							/datum/design/item/weapon/gun/launcher/confetti_cannon
							)

/obj/item/weapon/circuitboard/protolathe/security
	name = T_BOARD("protolathe")

/obj/item/weapon/circuitboard/protolathe/engineering
	name = T_BOARD("protolathe")

/obj/item/weapon/circuitboard/protolathe/service
	name = T_BOARD("protolathe")

/obj/item/weapon/circuitboard/protolathe/cargo
	name = T_BOARD("protolathe")

/obj/item/weapon/circuitboard/protolathe/medical
	name = T_BOARD("protolathe")

/obj/item/weapon/circuitboard/protolathe/exploration
	name = T_BOARD("protolathe")

/obj/item/weapon/circuitboard/protolathe/science
	name = T_BOARD("protolathe")
